import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "app/components/shared/Header";
import { Footer } from "app/components/shared/Footer";
import { ChackraProvider } from "app/providers/chacka-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChackraProvider>
          <Header />
          {children}
          <Footer />
        </ChackraProvider>
      </body>
    </html>
  );
}
